import { ReactNode, useState } from "react";
import { RangeEvent, RangeAssignment, RangeExcusalRequest } from "../../api/ranges";
import { AssignmentRow, RosterSection } from "../planning";
import RangeAttendancePanel from "./RangeAttendancePanel";
import SoldierSearchAutocomplete from "../SoldierSearchAutocomplete";
import { SoldierDTO } from "../../api/soldiers";
interface Props { event: RangeEvent; canManage: boolean; userId?: string; soldierName: (id:string)=>string; soldiers?: SoldierDTO[]; excusalRequests?: RangeExcusalRequest[]; shortfall: number|null; onAutoAssign:()=>Promise<void>; onConfirmDraft:(id:string)=>Promise<void>; onConfirmAll:()=>Promise<void>; onAdd:(s:SoldierDTO|null,reserve:boolean)=>Promise<void>; onRemove:(id:string)=>Promise<void>; onExcuse:(id:string,reason:string)=>Promise<void>; onDecide:(id:string,approve:boolean)=>Promise<void>; onAttendance:()=>void; actions?: ReactNode; }
export default function RangeDetailContent(p: Props) { const {event}=p; const primary=event.assignments.filter(a=>!a.is_reserve); const reserve=event.assignments.filter(a=>a.is_reserve); const [picker,setPicker]=useState(false); const [reserveToggle,setReserveToggle]=useState(false); const [reason,setReason]=useState(""); const [excuseId,setExcuseId]=useState<string|null>(null); const planned=event.status==="planned";
  const assignment=(a:RangeAssignment)=><div key={a.id}><AssignmentRow assignment={{id:a.id,soldierId:a.soldier_id,soldierName:p.soldierName(a.soldier_id),isDraft:a.is_draft,status:a.attendance_status}} detailSlot={<>{a.is_reserve&&<span className="text-xs">רזרבה</span>}{a.is_draft&&<span data-testid="draft-badge" className="text-xs">טיוטה</span>}</>} actionSlot={<span className="flex gap-1">{planned&&a.is_draft&&p.canManage&&<button data-testid="confirm-draft-button" onClick={()=>p.onConfirmDraft(a.id)}>אשר</button>}{p.canManage&&planned&&<button onClick={()=>p.onRemove(a.id)} className="text-red-600">הסר</button>}{p.userId===a.soldier_id&&planned&&!a.is_draft&&<button data-testid={`excuse-button-${a.id}`} onClick={()=>setExcuseId(a.id)}>לא אוכל להגיע</button>}</span>} />{excuseId===a.id&&<span className="flex gap-1"><input aria-label="סיבת היעדרות" value={reason} onChange={e=>setReason(e.target.value)} /><button data-testid="submit-excuse-button" disabled={!reason.trim()} onClick={()=>{p.onExcuse(a.id,reason);setReason("");setExcuseId(null)}}>שלח</button></span>}</div>;
  return <div className="space-y-3">{p.shortfall!==null&&<div data-testid="shortfall-banner" className="rounded bg-amber-100 px-3 py-2">לא נמצאו מספיק מועמדים — חסרים {p.shortfall} שיבוצים</div>}{p.actions}<div className="rounded bg-gray-50 p-3 text-sm dark:bg-gray-700"><div><b>הוראות הגעה:</b> {event.arrival_instructions||"—"}</div><div><b>איש קשר:</b> {event.contact_name||"—"} {event.contact_phone||""}</div><div><b>הערות:</b> {event.notes||"—"}</div></div>{p.canManage&&planned&&<div className="flex flex-wrap gap-2"><button data-testid="auto-assign-button" onClick={p.onAutoAssign}>שיבוץ אוטומטי</button>{event.assignments.some(a=>a.is_draft)&&<button data-testid="confirm-all-button" onClick={p.onConfirmAll}>אשר הכל</button>}<button data-testid="add-soldier-button" onClick={()=>setPicker(true)}>הוסף חייל</button></div>}{picker&&<div><label><input type="checkbox" data-testid="reserve-toggle" checked={reserveToggle} onChange={e=>setReserveToggle(e.target.checked)}/> שיבוץ כרזרבה</label><SoldierSearchAutocomplete onSelect={s=>p.onAdd(s,reserveToggle)}/></div>}<RosterSection kind="primary" assignments={primary.map(a=>({id:a.id,soldierId:a.soldier_id,soldierName:p.soldierName(a.soldier_id),isDraft:a.is_draft,status:a.attendance_status}))} count={event.required_count} assignmentActionRenderer={a=>{const x=primary.find(v=>v.id===a.id);return x?assignment(x):null}} />{primary.length===0&&<p className="text-sm text-gray-500">אין חיילים משובצים</p>}<RosterSection kind="reserve" assignments={reserve.map(a=>({id:a.id,soldierId:a.soldier_id,soldierName:p.soldierName(a.soldier_id),isDraft:a.is_draft,status:a.attendance_status}))} count={event.reserve_count} assignmentActionRenderer={a=>{const x=reserve.find(v=>v.id===a.id);return x?assignment(x):null}} />{p.excusalRequests&&p.excusalRequests.length>0&&<section data-testid="excusal-review-queue"><h3>בקשות היעדרות</h3>{p.excusalRequests.map(r=><div key={r.id}>{r.reason}<button data-testid={`approve-excusal-${r.id}`} onClick={()=>p.onDecide(r.id,true)}>אשר וקדם</button><button data-testid={`reject-excusal-${r.id}`} onClick={()=>p.onDecide(r.id,false)}>דחה</button></div>)}</section>}{p.canManage&&event.date<=new Date().toISOString().slice(0,10)&&<RangeAttendancePanel eventId={event.id} assignments={event.assignments.filter(a=>!a.is_draft)} soldierName={p.soldierName} onMarked={p.onAttendance}/>}</div>;
}





