[mypy]
python_version = 3.12
strict = true
plugins = pydantic.mypy
warn_unused_ignores = true

[mypy-tests.*]
disallow_untyped_decorators = false

[mypy-app.algorithm.model]
ignore_errors = True

[mypy-ortools.*]
ignore_missing_imports = True
