apiVersion: v1
kind: Service
metadata:
  name: justice-backend
  labels:
    app: justice-backend
spec:
  selector:
    app: justice-backend
  ports:
    - name: http
      port: 8000
      targetPort: 8000
