import { useMemo, useState } from "react";
import { useSearchParams } from "react-router-dom";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { addRangeAssignment, autoAssignRange, cancelRangeEvent, confirmAllDrafts, confirmDraftAssignment, createRangeEvent, decideRangeExcusal, deleteRangeEvent, excuseRangeAssignment, getRangeEvent, getRangeExcusalRequests, getRanges, CreateRangeEventBody, UpdateRangeEventBody, RangeEvent, RangeType, removeRangeAssignment, updateRangeEvent } from "../api/ranges";
import { queryKeys } from "../queryKeys"; import { useAuth } from "../auth/AuthContext"; import { canPlan } from "../auth/permissions";
import Layout from "../components/Layout"; import { EventDetailModal } from "../components/planning"; import RangePlanningTable from "../components/ranges/RangePlanningTable"; import RangeDetailContent from "../components/ranges/RangeDetailContent"; import RangeFormModal from "../components/ranges/RangeFormModal"; import RangeCancelDialog from "../components/ranges/RangeCancelDialog"; import { listSoldiers, SoldierDTO } from "../api/soldiers"; import { RANGE_TYPE_LABELS, RANGE_EVENT_STATUS_LABELS } from "../utils/rangeLabels";
export default function RangesPage(){ const [params]=useSearchParams(); const [selected,setSelected]=useState<string|null>(params.get("event")); const [formEvent,setFormEvent]=useState<RangeEvent|null|undefined>(undefined); const [cancelId,setCancelId]=useState<string|null>(null); const [type,setType]=useState<RangeType|"">(""); const [status,setStatus]=useState(""); const [fill,setFill]=useState(""); const [from,setFrom]=useState(""); const [to,setTo]=useState(""); const [sortAsc,setSortAsc]=useState(true); const qc=useQueryClient(); const {user}=useAuth(); const nodeId=user?.hierarchy_node_id??null; const manage=canPlan(user); const ranges=useQuery({queryKey:queryKeys.ranges(),queryFn:()=>getRanges(nodeId as string),enabled:!!nodeId}); const event=useQuery({queryKey:queryKeys.rangeEvent(selected as string),queryFn:()=>getRangeEvent(selected as string),enabled:!!selected}); const excusal=useQuery({queryKey:queryKeys.rangeExcusalRequests(selected as string),queryFn:()=>getRangeExcusalRequests(selected as string),enabled:!!selected&&!!user?.is_duty_manager}); const soldiers=useQuery({queryKey:queryKeys.soldiers(),queryFn:listSoldiers}); const names=(id:string)=>soldiers.data?.find(s=>s.id===id)?.full_name??id; const [shortfall,setShortfall]=useState<number|null>(null);
  const count=(e:RangeEvent,reserve:boolean)=>{const reported=reserve?e.reserve_filled:e.primary_filled;return reported??e.assignments.filter(a=>a.is_reserve===reserve&&!a.is_draft).length;};
  const rows=useMemo(()=>{const xs=(ranges.data??[]).filter(e=>(!type||e.range_type===type)&&(!status||e.status===status)&&(!from||e.date>=from)&&(!to||e.date<=to)&&(fill===""||(fill==="open"&&(count(e,false)<e.required_count||count(e,true)<e.reserve_count))||(fill==="full"&&count(e,false)>=e.required_count&&count(e,true)>=e.reserve_count))); return xs.sort((a,b)=>(a.date.localeCompare(b.date))*(sortAsc?1:-1));},[ranges.data,type,status,fill,from,to,sortAsc]); const invalidate=async(id?:string)=>{await qc.invalidateQueries({queryKey:queryKeys.ranges()});if(id)await qc.invalidateQueries({queryKey:queryKeys.rangeEvent(id)});};
  async function add(s:SoldierDTO|null,reserve:boolean){if(!s||!selected)return;await addRangeAssignment(selected,s.id,reserve);await invalidate(selected);}
  async function create(body:CreateRangeEventBody){await createRangeEvent(body);await invalidate();}
  async function save(body:CreateRangeEventBody|UpdateRangeEventBody){if(formEvent)await updateRangeEvent(formEvent.id,body);else {const createBody=body as CreateRangeEventBody;await create({hierarchy_node_id:createBody.hierarchy_node_id,range_type:createBody.range_type,date:createBody.date,location:createBody.location,required_count:Number(createBody.required_count),reserve_count:Number(createBody.reserve_count)});}await invalidate(formEvent?.id);}
  async function remove(id:string){if(!selected)return;await removeRangeAssignment(selected,id);await invalidate(selected)}
  async function attendance(){await invalidate(selected??undefined)}
  return <Layout><div className="space-y-4 p-4" dir="rtl"><div className="flex flex-wrap items-center justify-between gap-2"><h1 className="text-xl font-semibold">מטווחים</h1>{manage&&<button data-testid="create-event-button" onClick={()=>setFormEvent(null)} className="rounded bg-indigo-600 px-3 py-1.5 text-white">מטווח חדש</button>}</div><RangePlanningTable rows={rows} onRowClick={e=>{setSelected(e.id);setShortfall(null)}} rowActions={e=><div className="flex gap-2">{manage&&e.status==="planned"&&<><button data-testid={`edit-range-${e.id}`} onClick={()=>setFormEvent(e)}>ערוך</button><button data-testid={`delete-range-${e.id}`} onClick={async()=>{if(e.primary_filled===0&&e.reserve_filled===0&&confirm("למחוק?")){setSelected(current=>current===e.id?null:current);await deleteRangeEvent(e.id);await invalidate()}}}>מחק</button><button data-testid={`cancel-range-${e.id}`} onClick={()=>setCancelId(e.id)}>בטל</button></>}</div>} filters={<div className="flex flex-wrap gap-2"><input aria-label="מתאריך" type="date" value={from} onChange={e=>setFrom(e.target.value)}/><input aria-label="עד תאריך" type="date" value={to} onChange={e=>setTo(e.target.value)}/><select aria-label="סוג" value={type} onChange={e=>setType(e.target.value as RangeType|"")}><option value="">כל הסוגים</option>{Object.entries(RANGE_TYPE_LABELS).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><select aria-label="סטטוס" value={status} onChange={e=>setStatus(e.target.value)}><option value="">כל הסטטוסים</option>{Object.entries(RANGE_EVENT_STATUS_LABELS).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><select aria-label="מילוי" value={fill} onChange={e=>setFill(e.target.value)}><option value="">כל המצבים</option><option value="open">חסר</option><option value="full">מלא</option></select></div>} sort={<button onClick={()=>setSortAsc(v=>!v)}>מיון תאריך {sortAsc?"↑":"↓"}</button>} />
  {event.data&&<EventDetailModal open title={event.data.location} subtitle={`${RANGE_TYPE_LABELS[event.data.range_type]??event.data.range_type} · ${event.data.date}`} onClose={()=>setSelected(null)} metadata={[{label:"סטטוס",value:RANGE_EVENT_STATUS_LABELS[event.data.status]??event.data.status},{label:"שעות",value:`${event.data.start_time??"—"}–${event.data.end_time??"—"}`}]} actions={manage&&event.data.status==="planned"?<><button onClick={()=>setFormEvent(event.data)}>ערוך</button><button onClick={()=>setCancelId(event.data!.id)}>בטל</button></>:undefined}><RangeDetailContent event={event.data} canManage={manage} userId={user?.id} soldierName={names} soldiers={soldiers.data} excusalRequests={excusal.data} shortfall={shortfall} onAutoAssign={async()=>{const r=await autoAssignRange(event.data!.id);setShortfall(r.shortfall||null);await invalidate(event.data!.id)}} onConfirmDraft={async id=>{await confirmDraftAssignment(event.data!.id,id);await invalidate(event.data!.id)}} onConfirmAll={async()=>{await confirmAllDrafts(event.data!.id);await invalidate(event.data!.id)}} onAdd={add} onRemove={remove} onExcuse={async(id,reason)=>{await excuseRangeAssignment(event.data!.id,id,reason);await invalidate(event.data!.id);await qc.invalidateQueries({queryKey:queryKeys.rangeExcusalRequests(event.data!.id)})}} onDecide={async(id,approve)=>{await decideRangeExcusal(event.data!.id,id,approve);await invalidate(event.data!.id);await qc.invalidateQueries({queryKey:queryKeys.rangeExcusalRequests(event.data!.id)})}} onAttendance={attendance}/></EventDetailModal>}
  <RangeFormModal open={formEvent!==undefined} event={formEvent} hierarchyNodeId={nodeId??""} onClose={()=>setFormEvent(undefined)} onSubmit={save}/><RangeCancelDialog open={!!cancelId} onClose={()=>setCancelId(null)} onConfirm={async reason=>{if(cancelId){await cancelRangeEvent(cancelId,reason);await invalidate(cancelId)}}}/></div></Layout>;
}
