events {}
http {
 access_log /dev/stdout;
 error_log /dev/stderr warn;
 server {
  listen 9443 ssl;
  server_name seaweedfs;
  ssl_certificate /run/certs/seaweedfs.crt;
  ssl_certificate_key /run/certs/seaweedfs.key;
  ssl_protocols TLSv1.2 TLSv1.3;
  client_max_body_size 600m;
  location / {
   proxy_pass https://127.0.0.1:8334;
   proxy_http_version 1.1;
   proxy_set_header Host $http_host;
   proxy_set_header Connection "";
   proxy_request_buffering off;
   proxy_buffering off;
   proxy_ssl_server_name on;
   proxy_ssl_name seaweedfs;
   proxy_ssl_trusted_certificate /run/certs/ca.crt;
   proxy_ssl_verify on;
   proxy_ssl_verify_depth 2;
   proxy_read_timeout 300s;
   proxy_send_timeout 300s;
  }
 }
}
