// frontend/src/queryKeys.ts
//
// Central registry of react-query cache keys. Add a new entry here whenever a
// page starts fetching a new piece of server data — this keeps invalidation
// call sites (in mutations) and read sites (in useQuery calls) referring to
// the exact same key shape instead of hand-typed arrays that can drift apart.

export const queryKeys = {
  effectiveDuties: (soldierId: string, params?: Record<string, unknown>) =>
    ["effectiveDuties", soldierId, params ?? {}] as const,
  dutyTypes: () => ["dutyTypes"] as const,
  dutyLocations: () => ["dutyLocations"] as const,
  mySwaps: () => ["swaps", "mine"] as const,
  incomingSwaps: () => ["swaps", "incoming"] as const,
  pendingSwaps: () => ["swaps", "pending"] as const,
  swapBoard: (filters?: Record<string, unknown>) => ["swaps", "board", filters ?? {}] as const,
  pendingEnrollments: () => ["enrollment", "pending"] as const,
  pendingHierarchyTransfers: () => ["hierarchyTransfers", "pending"] as const,
  systemSettings: () => ["systemSettings"] as const,
  transparency: () => ["scoring", "transparency"] as const,
  breakdown: (soldierId: string) => ["scoring", "breakdown", soldierId] as const,
  reserveStats: () => ["soldiers", "reserveStats"] as const,
  pendingConstraintsCount: () => ["constraints", "pendingCount"] as const,
  pendingExemptionsCount: () => ["exemptions", "pendingCount"] as const,
  pendingFieldUpdatesCount: () => ["soldiers", "pendingFieldUpdatesCount"] as const,
  myConstraints: () => ["constraints", "mine"] as const,
  remainingConstraintDays: () => ["constraints", "remaining"] as const,
  myExemptionRequests: () => ["exemptionRequests", "mine"] as const,
  pendingConstraints: () => ["constraints", "pending"] as const,
  pendingExemptionRequests: () => ["exemptionRequests", "pending"] as const,
  pendingFieldUpdates: () => ["soldiers", "pendingFieldUpdates"] as const,
  hierarchyTree: () => ["hierarchy", "tree"] as const,
  publicExemptionTypes: () => ["exemptionTypes", "public"] as const,
  swapConfig: () => ["swaps", "config"] as const,
  swapCoverEligibility: (ids: string[]) => ["swaps", "coverEligibility", ids] as const,
  exemptionTypes: () => ["exemptionTypes"] as const,
  exemptionDutyTypeMap: () => ["exemptionTypes", "dutyTypeMap"] as const,
  exemptionDutyLocationMap: () => ["exemptionTypes", "dutyLocationMap"] as const,
  myExemptions: (soldierId: string) => ["exemptions", "mine", soldierId] as const,
  fieldUpdates: (soldierId: string) => ["soldiers", "fieldUpdates", soldierId] as const,
  ranks: () => ["soldiers", "ranks"] as const,
  telegramStatus: () => ["telegram", "status"] as const,
  notificationPreferences: () => ["notifications", "preferences"] as const,
  commanderScopes: () => ["notifications", "commanderScopes"] as const,
  hierarchyTreeVisible: () => ["hierarchy", "tree", "visible"] as const,
  notificationsList: () => ["notifications", "list"] as const,
  notifications: (filter: string, offset: number) => ["notifications", "list", filter, offset] as const,
  announceScope: () => ["notifications", "announceScope"] as const,
  announcementsList: (offset: number) => ["notifications", "announcements", offset] as const,
  announcementRecipients: (id: string) => ["notifications", "announcements", id, "recipients"] as const,
  soldiers: () => ["soldiers", "list"] as const,
  commandDashboardSummary: () => ["commandDashboard", "summary"] as const,
  commandDashboardSoldiers: () => ["commandDashboard", "soldiers"] as const,
  commandDashboardFairnessInternal: () => ["commandDashboard", "fairnessInternal"] as const,
  commandDashboardFairnessExternal: () => ["commandDashboard", "fairnessExternal"] as const,
  commandDashboardPotential: () => ["commandDashboard", "potential"] as const,
  commandDashboardUpcoming: () => ["commandDashboard", "upcoming"] as const,
  commandDashboardAlerts: () => ["commandDashboard", "alerts"] as const,
  commandDashboardOwnPotentialAll: () => ["commandDashboard", "ownPotential"] as const,
  commandDashboardOwnPotential: (nodeId: string) => ["commandDashboard", "ownPotential", nodeId] as const,
  assignments: (soldierId: string, params?: Record<string, unknown>) =>
    ["assignments", soldierId, params ?? {}] as const,
  draftsPreview: () => ["algorithm", "draftsPreview"] as const,
  shiftTemplates: () => ["shiftTemplates"] as const,
  shiftTemplatesAll: () => ["shiftTemplates", "all"] as const,
  shiftsList: () => ["shifts", "list"] as const,
  shifts: (params?: Record<string, unknown>) => ["shifts", "list", params ?? {}] as const,
  algorithmJobs: (limit: number, offset: number) => ["algorithm", "jobs", limit, offset] as const,
  algorithmJob: (jobId: string) => ["algorithm", "job", jobId] as const,
  soldierDetail: (soldierId: string) => ["soldiers", "detail", soldierId] as const,
  fairnessComponents: () => ["scoring", "fairnessComponents"] as const,
  effortGapNodes: (referenceDate?: string) => ["potential", "effortGap", referenceDate ?? null] as const,
  effortBreakdown: (soldierId: string) => ["scoring", "effortBreakdown", soldierId] as const,
  inviteCodes: () => ["inviteCodes"] as const,
  importSessionsList: () => ["import", "sessions"] as const,
  importSessions: (statusFilter?: string) => ["import", "sessions", statusFilter ?? "active"] as const,
  importSessionDetail: (sessionId: string) => ["import", "session", sessionId] as const,
  importDutyTypesForImport: () => ["import", "dutyTypesForImport"] as const,
  importNodesForImport: () => ["import", "nodesForImport"] as const,
  potentialByNode: (nodeId: string, referenceDate: string) => ["potential", "byNode", nodeId, referenceDate] as const,
  potentialModifiers: (nodeId: string) => ["potential", "modifiers", nodeId] as const,
  scoreAdjustments: (soldierId: string) => ["scoreAdjustments", soldierId] as const,
  soldierScore: (soldierId: string) => ["soldiers", "score", soldierId] as const,
  registrationPublicSettings: () => ["registrationPublicSettings"] as const,
  myBugReports: () => ["bugReports", "mine"] as const,
  myBugReportsUnseenCount: () => ["bugReports", "unseenCount"] as const,
  bugReportComments: (reportId: string) => ["bugReports", "comments", reportId] as const,
  ranges: () => ["ranges"] as const,
  rangeEvent: (id: string) => ["ranges", id] as const,
  rangeExcusalRequests: (id: string) => ["ranges", id, "excusal-requests"] as const,
  rangeLocations: () => ["rangeLocations"] as const,
  ineligibleSoldiers: (audience: "planning" | "commander") =>
    ["ranges", "ineligibleSoldiers", audience] as const,
  ineligibleSoldierCount: () => ["ranges", "ineligibleSoldiers", "count"] as const,
};
